trigger:
- main

pool:
  vmImage: 'ubuntu-latest'

stages:

- stage: Build
  jobs:
  - job: BuildJob
    steps:
    - script: mvn clean package -DskipTests
      displayName: 'Build Project'

- stage: Test
  dependsOn: Build
  jobs:
  - job: TestJob
    steps:
    - script: mvn test
      displayName: 'Run Tests'

    - task: PublishTestResults@2
      inputs:
        testResultsFiles: '**/surefire-reports/TEST-*.xml'